name: SkyPrestige
version: '${version}'
main: com.github.lukesky19.skyPrestige.SkyPrestige
api-version: '1.21'
authors: [ lukeskywlker19 ]

depend:
    - BentoBox
    - SkyLib
softdepend:
    - ExcellentCrates
    - LuckPerms
    - PlaceholderAPI
    - PlayerAuctions
    - Quests
    - RoseStacker
    - SkyEnchants
    - SkyHoppers
    - SkyShop
    - SkyPlayTime
    - SkySellWands
    - Vault