name: SkyPrestige
version: '${version}'
main: com.github.lukesky19.skyPrestige.SkyPrestige
api-version: '1.21'
authors: [ lukeskywlker19 ]

depend: [ BentoBox, SkyLib ]
softdepend: [ PlaceholderAPI, PlayerAuctions, RoseStacker, SkyPlayTime, SkySellWands, Vault ]

permissions:
    skyprestige.commands.skyprestige:
        description: Base Command Permission
        default: op
    skyprestige.commands.skyprestige.exchange:
        description: Permission to open the GUI to exchange prestige points.
        default: op
    skyprestige.commands.skyprestige.exempt:
        description: Permission to mark an island as exempt from the prestige leaderboard.
        default: op
    skyprestige.commands.skyprestige.help:
        description: Permission to view the plugin's help message.
        default: op
    skyprestige.commands.skyprestige.info:
        description: Permission to open the info GUI.
        default: op
    skyprestige.commands.skyprestige.leaderboard:
        description: Permission to view the prestige leaderboard.
        default: op
    skyprestige.commands.skyprestige.level:
        description: Permission to view and manage prestige levels.
        default: op
    skyprestige.commands.skyprestige.multiplier:
        description: Permission to manage and view information related to the prestige points multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.event:
        description: Permission to view either the remaining event time, the time until the next event, or if the event is disabled.
        default: op
    skyprestige.commands.skyprestige.multiplier.add:
        description: Permission to add to the current additional multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.remove:
        description: Permission to remove from the current additional multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.set:
        description: Permission to set the current additional multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.get:
        description: Permission to get the current multipliers.
        default: op
    skyprestige.commands.skyprestige.multiplier.get.additional:
        description: Permission to get the current additional multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.get.event:
        description: Permission to get the current event multiplier.
        default: op
    skyprestige.commands.skyprestige.multiplier.get.total:
        description: Permission to get the current total multiplier.
        default: op
    skyprestige.commands.skyprestige.points:
        description: Permission to view and manage prestige points.
        default: op
    skyprestige.commands.skyprestige.points.add:
        description: Permission to add prestige points.
        default: op
    skyprestige.commands.skyprestige.points.remove:
        description: Permission to remove prestige points.
        default: op
    skyprestige.commands.skyprestige.points.set:
        description: Permission to set prestige points.
        default: op
    skyprestige.commands.skyprestige.points.get:
        description: Permission to get prestige points.
        default: op
    skyprestige.commands.skyprestige.progress:
        description: Permission to view prestige progress.
        default: op
    skyprestige.commands.skyprestige.reload:
        description: Permission to reload the plugin.
        default: op
    skyprestige.commands.skyprestige.requirements:
        description: Permission to view prestige level requirements.
        default: op
    skyprestige.commands.skyprestige.rewards:
        description: Permission to view rewards for the next prestige level.
        default: op
    skyprestige.commands.skyprestige.unexempt:
        description: Permission to mark an island as not exempt from the prestige leaderboard.
        default: op
    skyprestige.commands.skyprestige.values:
        description: Permission to open the values GUI.
        default: op
    skyprestige.commands.skyprestige.vault:
        description: Permission to open the island vault.
        default: op