# DO NOT TOUCH! This is used to update the config file format if needed.
config-version: 2.0.0.0
# The file in SkyPrestige/locale to use.
locale: en_US
# How frequently island data is periodically saved. Island data are also saved on player disconnect and server shutdown.
save-frequency-seconds: 900
# The required prestige level necessary to exchange prestige points.
exchange-prestige-level: 0
# These settings apply when an island is reset outside of prestige, opt-in, or opt-out.
island-reset-settings:
    keep-island-size: true
    keep-generator-upgrades: true
    keep-island-flags: true
    reset-prestige-points: true
    reset-prestige-level: false
    clear-vault: false